//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabirovaAutoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Nullable<int> ID { get; set; }
        public string Наименование_услуги { get; set; }
        public string Главное_изображение { get; set; }
        public string Длительность { get; set; }
        public decimal Стоимость { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public string Описание { get; set; }
    }
}
